name: Static code analysis

on: [pull_request]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHPStan
        uses: docker://jakzal/phpqa:php8.1-alpine
        with:
          args: phpstan analyze src/ -l 1
      - name: Deptrac
        uses: docker://jakzal/phpqa:php8.1-alpine
        with:
          args: deptrac --no-interaction --ansi --formatter-graphviz-display=0